amqp:
  admin:
    auto-create: ${AMQO_ADMIN_AUTO_CREATE}
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

keycloak:
  realm: ${KEYCLOAK_REALM}
  host: ${KEYCLOAK_HOST}

postgres:
  url: ${DB_POSTGRES_URL}
  username: ${DB_POSTGRES_USERNAME}
  password: ${DB_POSTGRES_PASSWORD}
  schema: ${DB_POSTGRES_SCHEMA}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none